### ISSUE TITLE
Non-interactive installs?

### ISSUE THREAD

**Issue by SamuelMarks** [progrium/dokku#1367]
After running:
```
wget https://raw.github.com/progrium/dokku/v0.3.22/bootstrap.sh
sudo DOKKU_TAG=v0.3.22 bash bootstrap.sh
```

Here are the last few lines of the response:
```
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Extracting templates from packages: 53%
Extracting templates from packages: 100%
Preconfiguring packages ...
: [1;24r(B)0[m[1;24r[H[J[1;1HPackage configuration[8;22H[1K ┌──────┤ Configuring dokku ├──────┐[9;22H[1K │[33C│[10;22H[1K │[33C│[11;22H[1K │[33C│[12;22H[1K │ Use the web-based config page?  │[13;22H[1K │[33C│[14;22H[1K │[6C[7m<Yes>[9C[m<No>[9C│[15;22H[1K │[33C│[16;22H[1K └─────────────────────────────────┘[14;31H
```

Is there an easy way to get non-interactive installs working?

**Comment by josegonzalez** [comment]
You can use [debconf](http://progrium.viewdocs.io/dokku/getting-started/install/debian/) to setup unattended installation.

**Comment by rcarmo** [comment]
I'd like to re-open this, since even after setting options via `debconf` and using `DEBIAN_FRONTEND=noninteractive`, trying to automate an install using ansible still hangs with a `whiptail` process trying to request user input.

Here's part of my ansible playbook:

```yaml
---
- name: fetch bootstrap script
  get_url: url=https://raw.github.com/progrium/dokku/v0.3.22/bootstrap.sh dest=/tmp/bootstrap.sh

- name: debconf settings
  command: echo \"dokku {{ item }}\" | debconf-set-selections
  with_items:
    - "dokku/web_config boolean false"
    - "dokku/vhost_enable boolean true"
    - "dokku/hostname string {{ dokku_vhost }}"
    - "dokku/key_file string /root/.ssh/id_rsa.pub"
  sudo: yes

- name: install stable release
  command: "sudo DOKKU_TAG={{ dokku_version }} DEBIAN_FRONTEND=noninteractive bash /tmp/bootstrap.sh"
  sudo: yes
```
